[Variables]
FontColor=255,255,255,255
FontColorHi=255,255,255,255
FontSize=12
FontDebugSize=10
FontDateSize=14
FontFace=Raleway Medium
ColorText=255,255,255,255
ColorTextHi=255,255,255,255
SolidWhite=255,255,255,255
SolidOffWhite=242,242,242,255
SolidGreyText=178,178,178,255

[StyleWhiteText]
FontColor=#SolidWhite#

[StyleLeftAlign]
StringAlign=Left

[StyleRightAlign]
StringAlign=Right

[StyleCenterAlign]
StringAlign=Center

[StyleMediumText]
AntiAlias=1
FontFace=#FontFace#
FontSize=#FontDebugSize#
FontColor=#SolidWhite#
SolidColor=47,47,47,255
StringAlign=Left
ClipString=0

[StyleSmallText]
AntiAlias=1
FontFace=#FontFace#
FontSize=#FontDebugSize#
FontColor=#SolidGreyText#
SolidColor=47,47,47,255
StringAlign=Left
ClipString=0
;-------------------------------

[prayTime]
StringAlign=RIGHT
StringEffect=SHADOW
FontEffectColor=0,0,0,80
FontColor=#FontColor#
FontFace=Raleway Light
FontSize=#FontSize#
AntiAlias=1

[prayTimeHigh]
StringAlign=RIGHT
StringStyle=BOLD
StringEffect=SHADOW
FontEffectColor=0,0,0,80
FontColor=#FontColorHi#
FontFace=Raleway Black
FontSize=#FontSize#
AntiAlias=1

[prayTitle]
StringAlign=RIGHT
StringCase=NONE
StringEffect=SHADOW
FontEffectColor=0,0,0,80
FontColor=#ColorText#
FontFace=#FontFace#
FontSize=#FontSize#
AntiAlias=1

[prayTitleHigh]
StringStyle=BOLD
StringAlign=RIGHT
StringCase=NONE
StringEffect=SHADOW
FontEffectColor=0,0,0,80
FontColor=#ColorTextHi#
FontFace=#FontFace#
FontSize=#FontSize#
AntiAlias=1

[hijriDate]
StringAlign=RIGHT
StringStyle=BOLD
StringEffect=SHADOW
FontEffectColor=100,100,100,80
FontColor=#FontColor#
FontFace=#FontFace#
FontSize=#FontDateSize#
AntiAlias=1
StringCase=LOWER

