[Variables]
FontColor=255,255,255,255
FontColorHi=255,255,255,255
FontSize=12
FontDateSize=14
FontFace=Raleway Medium
ColorText=255,255,255,255
ColorTextHi=255,255,255,255

;-------------------------------

[prayTime]
StringAlign=RIGHT
StringEffect=SHADOW
FontEffectColor=0,0,0,80
FontColor=#FontColor#
FontFace=Raleway Light
FontSize=#FontSize#
AntiAlias=1
; SolidColor=47,47,47,255
; Padding=5,5,5,5

[prayTimeHigh]
StringAlign=RIGHT
StringStyle=BOLD
StringEffect=SHADOW
FontEffectColor=0,0,0,80
FontColor=#FontColorHi#
FontFace=Raleway Black
FontSize=#FontSize#
AntiAlias=1
; SolidColor=47,47,47,255
; Padding=5,5,5,5

[prayTitle]
StringAlign=RIGHT
StringCase=NONE
StringEffect=SHADOW
FontEffectColor=0,0,0,80
FontColor=#ColorText#
FontFace=#FontFace#
FontSize=#FontSize#
AntiAlias=1
; SolidColor=47,47,47,255
; Padding=5,5,5,5

[prayTitleHigh]
StringStyle=BOLD
StringAlign=RIGHT
StringCase=NONE
StringEffect=SHADOW
FontEffectColor=0,0,0,80
FontColor=#ColorTextHi#
FontFace=#FontFace#
FontSize=#FontSize#
AntiAlias=1
; SolidColor=47,47,47,255
; Padding=5,5,5,5

[hijriDate]
StringAlign=RIGHT
StringStyle=BOLD
StringEffect=SHADOW
FontEffectColor=100,100,100,80
FontColor=#FontColor#
FontFace=#FontFace#
FontSize=#FontDateSize#
AntiAlias=1
StringCase=LOWER
; SolidColor=47,47,47,255
; Padding=5,5,5,5

